# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

install: ./travis_install.rb 
language: cpp
compiler: clang
sudo: false